##Build CNN model and apply classification on MNIST-fashion dataset 





pipeline of cnn:<br>
1. understand the input & output(input image size)<br>
2. Train image and test image must have same size. As our model was trained on particular image size
3. If images are grayscale add fourth dimension to it(grayscale:fourth dimension is 1, RGB: fourth dimension is 3).
4. Normalize the image pixels by dividing it with 255
5. build cnn model layers and train and test on it.


In [ ]:
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
import numpy as np
from tensorflow.keras.datasets import fashion_mnist
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.optimizers import Adam 


In [ ]:
batch_size = 128
num_classes = 10
epochs = 15
class_names=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']

img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [ ]:

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# If images are grayscale add fourth dimension to it
x_train = x_train.reshape(60000,28,28,1)
x_test = x_test.reshape(10000,28,28,1)

# convert class vectors to binary class matrices
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

x_train shape: (60000, 28, 28)
60000 train samples
10000 test samples


In [ ]:
x_train=x_train/255.0
x_test=x_test/255.0

In [ ]:
#plt.imshow(x_test[0].reshape(28,28))

op = ((input - kernel size + 2*padding) / stride ) + 1

In [ ]:
# Padding = same: same as input size image after convolution 
# padding = valid: No padding --reduced size picture 
# filters = no of filters 
# kernel_size = filter size

fashion_mnist_model = tf.keras.models.Sequential()
fashion_mnist_model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding="same", activation="relu", input_shape=[28,28,1]))
fashion_mnist_model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding="same", activation="relu"))
fashion_mnist_model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))
fashion_mnist_model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding="same", activation="relu"))
fashion_mnist_model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding="same", activation="relu"))
fashion_mnist_model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))
# ANN model
fashion_mnist_model.add(tf.keras.layers.Flatten())
fashion_mnist_model.add(tf.keras.layers.Dropout(0.5,noise_shape=None,seed=None))
fashion_mnist_model.add(tf.keras.layers.Dense(units=128,activation='relu'))
fashion_mnist_model.add(tf.keras.layers.Dense(units=10,activation='softmax'))
fashion_mnist_model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_53 (Conv2D)          (None, 28, 28, 32)        320       
                                                                 
 conv2d_54 (Conv2D)          (None, 28, 28, 32)        9248      
                                                                 
 max_pooling2d_26 (MaxPoolin  (None, 14, 14, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_55 (Conv2D)          (None, 14, 14, 64)        18496     
                                                                 
 conv2d_56 (Conv2D)          (None, 14, 14, 64)        36928     
                                                                 
 max_pooling2d_27 (MaxPoolin  (None, 7, 7, 64)         0         
 g2D)                                                

In [ ]:
fashion_mnist_model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer=Adam(learning_rate = 0.0001))
fashion_mnist_model.fit(x_train,y_train,epochs=15)

Epoch 1/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.6390 - accuracy: 0.7684
Epoch 2/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.4013 - accuracy: 0.8558
Epoch 3/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.3464 - accuracy: 0.8761
Epoch 4/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.3147 - accuracy: 0.8866
Epoch 5/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.2876 - accuracy: 0.8958
Epoch 6/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.2689 - accuracy: 0.9021
Epoch 7/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.2525 - accuracy: 0.9093
Epoch 8/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.2361 - accuracy: 0.9128
Epoch 9/15
1875/1875 [==============================] - 25s 13ms/step - loss: 0.2263 - accuracy: 0.9169
Epoch 10/15
1875/1875 [==============================] - 25s 13m

In [ ]:
test_loss, test_accuracy = fashion_mnist_model.evaluate(x_test, y_test)

313/313 [==============================] - 2s 6ms/step - loss: 0.2059 - accuracy: 0.9253


In [ ]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.9253000020980835


## Build CNN model for Linneaus5 dataset (you can download 32*32 size images) link to download dataset - http://chaladze.com/l5/

In [ ]:
!unrar x "/content/Linnaeus 5 32X32.rar" "/content/"

Streaming output truncated to the last 5000 lines.
Extracting  /content/Linnaeus 5 32X32/train/berry/825_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/826_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/827_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/828_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/829_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/82_32.jpg               38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/830_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/831_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/832_32.jpg              38%  OK 
Extracting  /content/Linnaeus 5 32X32/train/berry/833_32.jpg              38%  OK 
Extracting  /content/Linnaeus

In [ ]:
import os
import pathlib
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf
from PIL import Image, ImageOps
from IPython.display import display
from sklearn.utils import shuffle
import matplotlib.pyplot as plt
from matplotlib import rcParams
import warnings


In [ ]:
# Used PIL library to process images 

#The numpy.ravel() functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it). A copy is made only if needed.
def process_image(img_path: str) -> np.array:
    img = Image.open(img_path)
    img = np.ravel(img) / 255.0  #numpy.ravel() == numpy.reshape(-1)
    return img

In [ ]:
def process_folder(folder: pathlib.PosixPath) -> pd.DataFrame:
    # We'll store the images here
    processed = []
    
    # For every image in the directory
    for img in folder.iterdir():
        # Ensure JPG
        if img.suffix == '.jpg':
            # Two images failed for whatever reason, so let's just ignore them
            try:
                processed.append(process_image(img_path=str(img)))
            except Exception as _:
                continue
           
    # Convert to pd.DataFrame
    classes = pd.DataFrame(processed)
    # Add a class column - dog or a cat
    classes['class'] = folder.parts[-1]
    
    return processed,classes

In [ ]:
# Training set
train_berry,classes1 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/berry'))
train_bird,classes2 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/bird'))
train_dog,classes3= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/dog'))
train_flower,classes4= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/flower'))
train_other,classes5= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/other'))

train_set = [train_berry,train_bird,train_dog,train_flower,train_other]


In [ ]:
x_train=np.array(train_set).reshape(6000, 32, 32,3)

In [ ]:
all_class=pd.concat([classes1, classes2,classes3,classes4,classes5], axis=0)
y_train = all_class['class']


In [ ]:
y_train=y_train.factorize()[0]
y_train

array([0, 0, 0, ..., 4, 4, 4])

In [ ]:
# Testing set
test_berry,classes1 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/berry'))
test_bird,classes2 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/bird'))
test_dog,classes3= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/dog'))
test_flower,classes4= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/flower'))
test_other,classes5= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/other'))

test_set = [test_berry,test_bird,test_dog,test_flower,test_other]

In [ ]:
x_test=np.array(test_set).reshape(2000, 32, 32,3)

In [ ]:
all_class=pd.concat([classes1,classes2,classes3,classes4,classes5], axis=0)
y_test = all_class['class']


In [ ]:
y_test=y_test.factorize()[0]
y_test

array([0, 0, 0, ..., 4, 4, 4])

In [ ]:
num_classes=5
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

In [ ]:
# Padding = same: same as input size image after convolution 
# padding = valid: No padding --reduced size picture 
# filters = no of filters 
# kernel_size = filter size

cnn_model = tf.keras.models.Sequential()
cnn_model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding="same", activation="relu", input_shape=[32,32,3]))
cnn_model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding="same", activation="relu"))
cnn_model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))
cnn_model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding="same", activation="relu"))
cnn_model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding="same", activation="relu"))
cnn_model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))
# ANN model
cnn_model.add(tf.keras.layers.Flatten())
cnn_model.add(tf.keras.layers.Dropout(0.5,noise_shape=None,seed=None))
cnn_model.add(tf.keras.layers.Dense(units=128,activation='relu'))
cnn_model.add(tf.keras.layers.Dense(units=5,activation='softmax'))
cnn_model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_57 (Conv2D)          (None, 32, 32, 32)        896       
                                                                 
 conv2d_58 (Conv2D)          (None, 32, 32, 32)        9248      
                                                                 
 max_pooling2d_28 (MaxPoolin  (None, 16, 16, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_59 (Conv2D)          (None, 16, 16, 64)        18496     
                                                                 
 conv2d_60 (Conv2D)          (None, 16, 16, 64)        36928     
                                                                 
 max_pooling2d_29 (MaxPoolin  (None, 8, 8, 64)         0         
 g2D)                                                

In [ ]:
cnn_model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer=Adam(learning_rate = 0.001))
cnn_model.fit(x_train,y_train,epochs=15)

Epoch 1/15
188/188 [==============================] - 3s 14ms/step - loss: 1.4220 - accuracy: 0.3545
Epoch 2/15
188/188 [==============================] - 3s 14ms/step - loss: 1.2305 - accuracy: 0.4820
Epoch 3/15
188/188 [==============================] - 3s 14ms/step - loss: 1.1069 - accuracy: 0.5427
Epoch 4/15
188/188 [==============================] - 3s 13ms/step - loss: 1.0156 - accuracy: 0.5858
Epoch 5/15
188/188 [==============================] - 2s 13ms/step - loss: 0.9522 - accuracy: 0.6197
Epoch 6/15
188/188 [==============================] - 2s 13ms/step - loss: 0.8676 - accuracy: 0.6600
Epoch 7/15
188/188 [==============================] - 2s 13ms/step - loss: 0.8195 - accuracy: 0.6777
Epoch 8/15
188/188 [==============================] - 2s 13ms/step - loss: 0.7672 - accuracy: 0.6982
Epoch 9/15
188/188 [==============================] - 3s 13ms/step - loss: 0.7056 - accuracy: 0.7263
Epoch 10/15
188/188 [==============================] - 3s 13ms/step - loss: 0.6308 - accura

In [ ]:
test_loss, test_accuracy = cnn_model.evaluate(x_test, y_test)

63/63 [==============================] - 1s 6ms/step - loss: 0.9314 - accuracy: 0.7025


In [ ]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.7024999856948853


## Train CNN on grayscale images and compare results with rgb image trained model(I've used above dataset)

In [ ]:
def process_image(img_path: str) -> np.array:
    img = Image.open(img_path)
    img = ImageOps.grayscale(img)
    img = img.resize(size=(32, 32))
    img = np.ravel(img) / 255.0
    return img

In [ ]:
def process_folder(folder: pathlib.PosixPath) -> pd.DataFrame:
    # We'll store the images here
    processed = []
    
    # For every image in the directory
    for img in folder.iterdir():
        # Ensure JPG
        if img.suffix == '.jpg':
            # Two images failed for whatever reason, so let's just ignore them
            try:
                processed.append(process_image(img_path=str(img)))
            except Exception as _:
                continue
           
    # Convert to pd.DataFrame
    classes = pd.DataFrame(processed)
    # Add a class column - dog or a cat
    classes['class'] = folder.parts[-1]
    
    return processed,classes

In [ ]:
# Training set
train_berry,classes1 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/berry'))
train_bird,classes2 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/bird'))
train_dog,classes3= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/dog'))
train_flower,classes4= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/flower'))
train_other,classes5= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/train/other'))

train_set = [train_berry,train_bird,train_dog,train_flower,train_other]


In [ ]:
x_train=np.array(train_set).reshape(6000, 32, 32,1)

In [ ]:
all_class=pd.concat([classes1, classes2,classes3,classes4,classes5], axis=0)
y_train = all_class['class']


In [ ]:
y_train=y_train.factorize()[0]
y_train

array([0, 0, 0, ..., 4, 4, 4])

In [ ]:
# Testing set
test_berry,classes1 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/berry'))
test_bird,classes2 = process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/bird'))
test_dog,classes3= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/dog'))
test_flower,classes4= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/flower'))
test_other,classes5= process_folder(folder=pathlib.Path.cwd().joinpath('/content/Linnaeus 5 32X32/test/other'))

test_set = [test_berry,test_bird,test_dog,test_flower,test_other]

In [ ]:
x_test=np.array(test_set).reshape(2000, 32, 32,1)

In [ ]:
all_class=pd.concat([classes1,classes2,classes3,classes4,classes5], axis=0)
y_test = all_class['class']


In [ ]:
y_test=y_test.factorize()[0]
y_test

array([0, 0, 0, ..., 4, 4, 4])

In [ ]:
num_classes=5
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

In [ ]:
# Padding = same: same as input size image after convolution 
# padding = valid: No padding --reduced size picture 
# filters = no of filters 
# kernel_size = filter size

cnn_model = tf.keras.models.Sequential()
cnn_model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding="same", activation="relu", input_shape=[32,32,1]))
cnn_model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding="same", activation="relu"))
cnn_model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))
cnn_model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding="same", activation="relu"))
cnn_model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding="same", activation="relu"))
cnn_model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))
# ANN model
cnn_model.add(tf.keras.layers.Flatten())
cnn_model.add(tf.keras.layers.Dropout(0.5,noise_shape=None,seed=None))
cnn_model.add(tf.keras.layers.Dense(units=128,activation='relu'))
cnn_model.add(tf.keras.layers.Dense(units=5,activation='softmax'))
cnn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        320       
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 16, 16, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 16, 16, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 16, 16, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 8, 8, 64)         0         
 2D)                                                    

In [ ]:
cnn_model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer=Adam(learning_rate = 0.001))
cnn_model.fit(x_train,y_train,epochs=15)

Epoch 1/15
188/188 [==============================] - 13s 13ms/step - loss: 1.5790 - accuracy: 0.2583
Epoch 2/15
188/188 [==============================] - 2s 11ms/step - loss: 1.4804 - accuracy: 0.3498
Epoch 3/15
188/188 [==============================] - 2s 11ms/step - loss: 1.4085 - accuracy: 0.4018
Epoch 4/15
188/188 [==============================] - 2s 11ms/step - loss: 1.3484 - accuracy: 0.4348
Epoch 5/15
188/188 [==============================] - 2s 11ms/step - loss: 1.2872 - accuracy: 0.4648
Epoch 6/15
188/188 [==============================] - 2s 11ms/step - loss: 1.1981 - accuracy: 0.5150
Epoch 7/15
188/188 [==============================] - 2s 11ms/step - loss: 1.1150 - accuracy: 0.5552
Epoch 8/15
188/188 [==============================] - 2s 11ms/step - loss: 1.0330 - accuracy: 0.5907
Epoch 9/15
188/188 [==============================] - 2s 11ms/step - loss: 0.9550 - accuracy: 0.6257
Epoch 10/15
188/188 [==============================] - 2s 11ms/step - loss: 0.8670 - accur

In [ ]:
test_loss, test_accuracy = cnn_model.evaluate(x_test, y_test)

63/63 [==============================] - 1s 6ms/step - loss: 1.4359 - accuracy: 0.5245


In [ ]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.5245000123977661
